In [6]:
import pandas as pd
from datetime import timedelta
# Load data
stop_time = pd.read_csv("C:/Users/z048523/myenv/stop_times.csv")

In [7]:
trips=pd.read_csv("C:/Users/z048523/myenv/trips.csv")

In [3]:
def parse_gtfs_time(t):
    h, m, s = map(int, t.split(":"))
    return timedelta(hours=h, minutes=m, seconds=s)

In [8]:
stop_time["departure_time_td"] = stop_time["departure_time"].apply(parse_gtfs_time)

In [9]:
route_17_trips = trips[trips["route_id"] == "17"]

In [11]:
merged = pd.merge(route_17_trips, stop_time, on="trip_id")

In [12]:
last_stops = merged.sort_values("stop_sequence").groupby("trip_id").last().reset_index()

In [14]:
last_stops

,trip_id,route_id,service_id,trip_headsign,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,shape_dist_traveled,timepoint,departure_time_td
0,0_11994959,17,0_1,Hôpital Schuman,0,1701,L17P1,1,2,05:45:00,05:45:00,0:HSCHUMA2,41,NaN,0,17702,1,0 days 05:45:00
1,0_11994960,17,0_1,Hôpital Schuman,0,1702,L17P1,1,2,06:45:00,06:45:00,0:HSCHUMA2,41,NaN,0,17702,1,0 days 06:45:00
2,0_11994961,17,0_1,Hôpital Schuman,0,1701,L17P1,1,2,07:44:00,07:44:00,0:HSCHUMA2,41,NaN,0,17702,1,0 days 07:44:00
3,0_11994962,17,0_1,Hôpital Schuman,0,1703,L17P1,1,2,08:04:00,08:04:00,0:HSCHUMA2,41,NaN,0,17702,1,0 days 08:04:00
4,0_11994963,17,0_1,Hôpital Schuman,0,1702,L17P1,1,2,08:44:00,08:44:00,0:HSCHUMA2,41,NaN,0,17702,1,0 days 08:44:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,0_61994992,17,0_6,Moulins Tournebride,1,1702,L17P2,1,2,17:45:00,17:45:00,0:TOURNEB1,41,NaN,0,17139,1,0 days 17:45:00
224,0_61994994,17,0_6,Moulins Tournebride,1,1701,L17P2,1,2,18:45:00,18:45:00,0:TOURNEB1,41,NaN,0,17139,1,0 days 18:45:00
225,0_61994995,17,0_6,Moulins Tournebride,1,1702,L17P2,1,2,19:43:00,19:43:00,0:TOURNEB1,41,NaN,0,17139,1,0 days 19:43:00
226,0_61994996,17,0_6,Moulins Tournebride,1,1701,L17P2,1,2,20:42:00,20:42:00,0:TOURNEB1,41,NaN,0,17139,1,0 days 20:42:00
227,0_61994997,17,0_6,Moulins Tournebride,1,1702,L17P2,1,2,21:50:00,21:50:00,0:TOURNEB1,41,NaN,0,17139,1,0 days 21:50:00

In [13]:
latest_departure = last_stops["departure_time_td"].max()
print("🕔 Last bus departure time for Route 17:", latest_departure)

🕔 Last bus departure time for Route 17: 0 days 21:50:00

In [15]:
route_1_trips = trips[trips["route_id"] == "1"]

In [16]:
merged = pd.merge(route_1_trips, stop_time, on="trip_id")

In [17]:
last_stops = merged.sort_values("stop_sequence").groupby("trip_id").last().reset_index()

In [18]:
latest_departure = last_stops["departure_time_td"].max()
print("🕔 Last bus departure time for Route 1:", latest_departure)

🕔 Last bus departure time for Route 1: 0 days 22:52:00

In [19]:
route_B_trips = trips[trips["route_id"] == "B"]

In [20]:
merged = pd.merge(route_B_trips, stop_time, on="trip_id")

In [22]:
last_stops = merged.sort_values("stop_sequence").groupby("trip_id").last().reset_index()

In [23]:
latest_departure = last_stops["departure_time_td"].max()
print("🕔 Last bus departure time for Route B:", latest_departure)

🕔 Last bus departure time for Route B: 1 days 00:45:00

In [26]:
route_17_trips = trips[trips["route_id"] == "17"]

# Merge with stop_times to get departure times
merged = pd.merge(route_17_trips, stop_time, on="trip_id")
first_stops = merged[merged["stop_sequence"] == 1]
sorted_departures = first_stops.sort_values("departure_time_td")
departure_times = sorted_departures["departure_time_td"].tolist()

# Calculate intervals
intervals = [ (departure_times[i+1] - departure_times[i]).total_seconds() / 60 for i in range(len(departure_times)-1) ]

# Calculate average frequency
average_frequency = sum(intervals) / len(intervals) if intervals else None

print("🚌 Average frequency of Route 17 (in minutes):", round(average_frequency, 2) if average_frequency else "Not enough data")

🚌 Average frequency of Route 17 (in minutes): 4.26

In [27]:
route_17_trips = trips[trips["route_id"] == "B"]

# Merge with stop_times to get departure times
merged = pd.merge(route_17_trips, stop_time, on="trip_id")
first_stops = merged[merged["stop_sequence"] == 1]
sorted_departures = first_stops.sort_values("departure_time_td")
departure_times = sorted_departures["departure_time_td"].tolist()

# Calculate intervals
intervals = [ (departure_times[i+1] - departure_times[i]).total_seconds() / 60 for i in range(len(departure_times)-1) ]

# Calculate average frequency
average_frequency = sum(intervals) / len(intervals) if intervals else None

print("🚌 Average frequency of Route 17 (in minutes):", round(average_frequency, 2) if average_frequency else "Not enough data")

🚌 Average frequency of Route 17 (in minutes): 1.21

In [28]:
route_17_trips = trips[trips["route_id"] == "1"]

# Merge with stop_times to get departure times
merged = pd.merge(route_17_trips, stop_time, on="trip_id")
first_stops = merged[merged["stop_sequence"] == 1]
sorted_departures = first_stops.sort_values("departure_time_td")
departure_times = sorted_departures["departure_time_td"].tolist()

# Calculate intervals
intervals = [ (departure_times[i+1] - departure_times[i]).total_seconds() / 60 for i in range(len(departure_times)-1) ]

# Calculate average frequency
average_frequency = sum(intervals) / len(intervals) if intervals else None

print("🚌 Average frequency of Route 17 (in minutes):", round(average_frequency, 2) if average_frequency else "Not enough data")

🚌 Average frequency of Route 17 (in minutes): 1.26

In [1]:
import pandas as pd
from geopy.distance import geodesic

# Load necessary GTFS files
routes = pd.read_csv("C:/Users/z048523/myenv/routes.csv")
trips = pd.read_csv("C:/Users/z048523/myenv/trips.csv")
stop_times = pd.read_csv("C:/Users/z048523/myenv/stop_times.csv")
stops = pd.read_csv("C:/Users/z048523/myenv/stops.csv")

In [15]:
import pandas as pd
from datetime import datetime



# Filter trips for route 17
route_17_trips = trips[trips['route_id'].astype(str) == "17"]
trip_ids_17 = route_17_trips['trip_id'].unique()

# Get stop times for route 17 trips
route_17_stop_times = stop_times[stop_times['trip_id'].isin(trip_ids_17)].copy()

# Merge with stop data to get stop names or coordinates if needed
route_17_stop_times = route_17_stop_times.merge(stops[['stop_id', 'stop_lat', 'stop_lon']], on='stop_id', how='left')

# Convert departure time to datetime (removing invalid values like 24:xx)
def parse_time(t):
    try:
        return datetime.strptime(t, "%H:%M:%S").time()
    except:
        return None

route_17_stop_times['departure_time'] = route_17_stop_times['departure_time'].apply(parse_time)
route_17_stop_times = route_17_stop_times.dropna(subset=['departure_time'])

# Count how many departures per hour
route_17_stop_times['hour'] = route_17_stop_times['departure_time'].apply(lambda t: t.hour)
frequency_by_hour = route_17_stop_times.groupby('hour').size()

In [16]:
# Unique trip IDs for each hour based on their first stop time
first_stops = route_17_stop_times.sort_values(['trip_id', 'stop_sequence']).groupby('trip_id').first().reset_index()

# Extract the hour of departure
first_stops['hour'] = first_stops['departure_time'].apply(lambda t: t.hour)

# Trips per hour
trips_per_hour = first_stops.groupby('hour').size()

# More accurate average
avg_frequency = trips_per_hour.mean()

print("✅ Unique trips on route 17:", len(first_stops))
print("✅ Average frequency (buses/hour):", round(avg_frequency, 2))
print("\n📊 Hourly breakdown:\n", trips_per_hour)

✅ Unique trips on route 17: 228
✅ Average frequency (buses/hour): 13.41

📊 Hourly breakdown:
 hour
5      6
6     12
7     22
8     17
9     12
10    12
11    12
12    12
13    12
14    12
15    12
16    17
17    22
18    12
19    12
20    12
21    12
dtype: int64

In [21]:
import pandas as pd
from datetime import datetime



# Filter trips for route 17
route_1_trips = trips[trips['route_id'].astype(str) == "1"]
trip_ids_1 = route_1_trips['trip_id'].unique()

# Get stop times for route 17 trips
route_1_stop_times = stop_times[stop_times['trip_id'].isin(trip_ids_1)].copy()

# Merge with stop data to get stop names or coordinates if needed
route_1_stop_times = route_1_stop_times.merge(stops[['stop_id', 'stop_lat', 'stop_lon']], on='stop_id', how='left')

# Convert departure time to datetime (removing invalid values like 24:xx)
def parse_time(t):
    try:
        return datetime.strptime(t, "%H:%M:%S").time()
    except:
        return None

route_1_stop_times['departure_time'] = route_1_stop_times['departure_time'].apply(parse_time)
route_1_stop_times = route_1_stop_times.dropna(subset=['departure_time'])

# Count how many departures per hour
route_1_stop_times['hour'] = route_1_stop_times['departure_time'].apply(lambda t: t.hour)
frequency_by_hour = route_1_stop_times.groupby('hour').size()

In [22]:
# Unique trip IDs for each hour based on their first stop time
first_stops = route_1_stop_times.sort_values(['trip_id', 'stop_sequence']).groupby('trip_id').first().reset_index()

# Extract the hour of departure
first_stops['hour'] = first_stops['departure_time'].apply(lambda t: t.hour)

# Trips per hour
trips_per_hour = first_stops.groupby('hour').size()

# More accurate average
avg_frequency = trips_per_hour.mean()

print("✅ Unique trips on route 1:", len(first_stops))
print("✅ Average frequency (buses/hour):", round(avg_frequency, 2))
print("\n📊 Hourly breakdown:\n", trips_per_hour)

✅ Unique trips on route 1: 838
✅ Average frequency (buses/hour): 46.56

📊 Hourly breakdown:
 hour
5     36
6     36
7     52
8     52
9     52
10    52
11    52
12    56
13    56
14    56
15    56
16    56
17    56
18    50
19    44
20    34
21    10
22    32
dtype: int64

In [23]:
import pandas as pd
from datetime import datetime



# Filter trips for route 17
route_b_trips = trips[trips['route_id'].astype(str) == "B"]
trip_ids_b = route_b_trips['trip_id'].unique()

# Get stop times for route 17 trips
route_b_stop_times = stop_times[stop_times['trip_id'].isin(trip_ids_b)].copy()

# Merge with stop data to get stop names or coordinates if needed
route_b_stop_times = route_b_stop_times.merge(stops[['stop_id', 'stop_lat', 'stop_lon']], on='stop_id', how='left')

# Convert departure time to datetime (removing invalid values like 24:xx)
def parse_time(t):
    try:
        return datetime.strptime(t, "%H:%M:%S").time()
    except:
        return None

route_b_stop_times['departure_time'] = route_b_stop_times['departure_time'].apply(parse_time)
route_b_stop_times = route_b_stop_times.dropna(subset=['departure_time'])

# Count how many departures per hour
route_b_stop_times['hour'] = route_b_stop_times['departure_time'].apply(lambda t: t.hour)
frequency_by_hour = route_b_stop_times.groupby('hour').size()

In [25]:
# Unique trip IDs for each hour based on their first stop time
first_stops = route_b_stop_times.sort_values(['trip_id', 'stop_sequence']).groupby('trip_id').first().reset_index()

# Extract the hour of departure
first_stops['hour'] = first_stops['departure_time'].apply(lambda t: t.hour)

# Trips per hour
trips_per_hour = first_stops.groupby('hour').size()

# More accurate average
avg_frequency = trips_per_hour.mean()

print("✅ Unique trips on route B:", len(first_stops))
print("✅ Average frequency (buses/hour):", round(avg_frequency, 2))
print("\n📊 Hourly breakdown:\n", trips_per_hour)

✅ Unique trips on route B: 940
✅ Average frequency (buses/hour): 49.47

📊 Hourly breakdown:
 hour
5     28
6     32
7     56
8     56
9     56
10    56
11    56
12    56
13    56
14    56
15    56
16    56
17    56
18    56
19    44
20    56
21    44
22    32
23    32
dtype: int64